- hosts: host
  become: yes
  tasks:
    - name: copy built files to deploy-server
      synchronize:
        src: /var/lib/jenkins/workspace/nodek/build/
        dest: /home/ubuntu/my-app/
        delete: true
        recursive: true

    - name: change-owner
      file:
        path: /home/ubuntu/my-app/
        owner: ubuntu
        group: ubuntu
        recurse: yes
        state: directory

    - name: start node
      shell: 
        chdir: /home/ubuntu/my-app/
        cmd: /bin/bash startnode.sh
      become: yes

  
